name: Deploy Legal Pages

on:
  push:
    branches:
      - main  # 只要你修改了 main 分支的文件，就自动更新到域名下
  workflow_dispatch: # 允许你手动点击运行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .               # 将仓库根目录所有文件发布
          branch: gh-pages        # 发布到 gh-pages 分支
          clean: false            # 保护已有的文件
